//
// Created by roger on 2020/12/25.
//

#ifndef VR720_CCERRORS_H
#define VR720_CCERRORS_H

#define VR_ERR_UN_KNOW 0 //FOR UI
#define VR_ERR_SUCCESS 1 //FOR UI
#define VR_ERR_FILE_NOT_EXISTS 2 //FOR UI
#define VR_ERR_FILE_NOT_SUPPORT 3 //FOR UI
#define VR_ERR_IMAGE_TOO_BIG 4 //FOR UI
#define VR_ERR_BIG_IMAGE_AND_NOT_JPG 5 //FOR UI
#define VR_ERR_BAD_IMAGE 6 //FOR UI

#define VR_ERR_VIDEO_PLAYER_NOW_IS_LOADING 26
#define VR_ERR_VIDEO_PLAYER_ALREADY_OPEN 27
#define VR_ERR_VIDEO_PLAYER_STATE_CAN_ONLY_GET 28
#define VR_ERR_VIDEO_PLAYER_NOT_OPEN 29
#define VR_ERR_VIDEO_PLAYER_AV_ERROR 30 //FOR UI
#define VR_ERR_VIDEO_PLAYER_NO_VIDEO_STREAM 31 //FOR UI
#define VR_ERR_VIDEO_PLAYER_VIDEO_NOT_SUPPORT 32 //FOR UI
#define VR_ERR_VIDEO_PLAYER_NOR_INIT 33

#endif //VR720_CCERRORS_H
