//
// Created by roger on 2020/12/22.
//

#ifndef VR720_CCPROPERTIES_H
#define VR720_CCPROPERTIES_H

#define PROP_IS_FILE_OPEN 2
#define PROP_IS_CURRENT_FILE_OPEN 3
#define PROP_CURRENT_FILE_IS_VIDEO 4

#define PROP_VR_ENABLED 12
#define PROP_GYRO_ENABLED 13
#define PROP_FULL_CHUNK_LOAD_ENABLED 14
#define PROP_VIEW_CACHE_ENABLED 15
#define PROP_CACHE_PATH 16
#define PROP_LAST_ERROR 17

#endif //VR720_CCPROPERTIES_H
