/* DO NOT EDIT THIS FILE - it is machine generated */
#include "stdafx.h"
/* Header for class com_imengyu_vr720_core_NativeVR720 */

#ifndef _Included_com_imengyu_vr720_core_NativeVR720
#define _Included_com_imengyu_vr720_core_NativeVR720
#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif
#endif
