/* DO NOT EDIT THIS FILE - it is machine generated */
#include "stdafx.h"
/* Header for class com_imengyu_vr720_core_NativeVR720 */

#ifndef _Included_com_imengyu_vr720_core_NativeVR720
#define _Included_com_imengyu_vr720_core_NativeVR720
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_imengyu_vr720_core_NativeVR720
 * Method:    initNative
 * Signature: ()Z
 */
extern "C" JNIEXPORT jboolean JNICALL Java_com_imengyu_vr720_core_NativeVR720_initNative
  (JNIEnv *, jclass, jobject assetManager);

/*
 * Class:     com_imengyu_vr720_core_NativeVR720
 * Method:    releaseNative
 * Signature: ()V
 */
extern "C" JNIEXPORT void JNICALL Java_com_imengyu_vr720_core_NativeVR720_releaseNative
  (JNIEnv *, jclass);

/*
 * Class:     com_imengyu_vr720_core_NativeVR720
 * Method:    getNativeVersion
 * Signature: ()Ljava/lang/String;
 */
extern "C" JNIEXPORT jstring JNICALL Java_com_imengyu_vr720_core_NativeVR720_getNativeVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
