/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dreamfish_com_vr720_core_NativeVR720 */

#ifndef _Included_com_dreamfish_com_vr720_core_NativeVR720
#define _Included_com_dreamfish_com_vr720_core_NativeVR720
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dreamfish_com_vr720_core_NativeVR720
 * Method:    initNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_dreamfish_com_vr720_core_NativeVR720_initNative
  (JNIEnv *, jclass);

/*
 * Class:     com_dreamfish_com_vr720_core_NativeVR720
 * Method:    releaseNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dreamfish_com_vr720_core_NativeVR720_releaseNative
  (JNIEnv *, jclass);

/*
 * Class:     com_dreamfish_com_vr720_core_NativeVR720
 * Method:    getNativeVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dreamfish_com_vr720_core_NativeVR720_getNativeVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
